const { DEFAULT_THEME_COLORS, normalizeThemeColors } = require('./themePalette');

const VARIANT_MAP = {
    brand: {
        badgeBg: '#eff6ff',
        badgeText: '#1d4ed8',
        accentBg: '#eef2ff',
        accentBorder: '#c7d2fe',
        accentText: '#4338ca',
        label: 'Institute update'
    },
    info: {
        primary: '#0f4c81',
        secondary: '#38bdf8',
        badgeBg: '#e0f2fe',
        badgeText: '#0369a1',
        accentBg: '#f0f9ff',
        accentBorder: '#bae6fd',
        accentText: '#075985',
        label: 'Information'
    },
    success: {
        primary: '#047857',
        secondary: '#34d399',
        badgeBg: '#dcfce7',
        badgeText: '#047857',
        accentBg: '#f0fdf4',
        accentBorder: '#86efac',
        accentText: '#166534',
        label: 'Success'
    },
    warning: {
        primary: '#b45309',
        secondary: '#f59e0b',
        badgeBg: '#fef3c7',
        badgeText: '#b45309',
        accentBg: '#fffbeb',
        accentBorder: '#fcd34d',
        accentText: '#92400e',
        label: 'Attention'
    },
    danger: {
        primary: '#b91c1c',
        secondary: '#f97316',
        badgeBg: '#fee2e2',
        badgeText: '#b91c1c',
        accentBg: '#fff7ed',
        accentBorder: '#fdba74',
        accentText: '#c2410c',
        label: 'Important'
    }
};

const NOTIFICATION_THEME_MAP = {
    general: 'brand',
    announcement: 'brand',
    studentRegistration: 'brand',
    teacherRegistration: 'brand',
    attendance: 'info',
    homework: 'info',
    exam: 'info',
    batchAssignment: 'info',
    teacherBatchAssignment: 'info',
    testAnnouncement: 'info',
    fee: 'warning',
    feeGenerated: 'warning',
    surchargeAdded: 'warning',
    feePayment: 'success',
    examResult: 'success',
    salaryPaid: 'success',
    feeOverdue: 'danger'
};

const escapeHtml = (value) => String(value || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

const stripTags = (value) => String(value || '').replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();

const isFullHtmlDocument = (value) => /<html[\s>]|<!doctype html/i.test(String(value || ''));

const hasInlineHtml = (value) => /<\/?[a-z][\s\S]*>/i.test(String(value || ''));

const formatBodyHtml = (message, allowHtml = false) => {
    const rawMessage = String(message || '').trim();

    if (!rawMessage) {
        return '<p style="margin: 0;">We wanted to share an update with you.</p>';
    }

    if (allowHtml && hasInlineHtml(rawMessage)) {
        return rawMessage;
    }

    return rawMessage
        .split(/\n{2,}/)
        .map((paragraph) => `<p style="margin: 0 0 16px;">${escapeHtml(paragraph).replace(/\n/g, '<br/>')}</p>`)
        .join('');
};

const resolveTemplateTheme = ({ admin, notificationType = 'general', palette }) => {
    if (Array.isArray(palette) && palette.length >= 2) {
        const [primary, secondary] = normalizeThemeColors(palette);
        const brandTheme = VARIANT_MAP.brand;
        return { ...brandTheme, primary, secondary };
    }

    const variantKey = NOTIFICATION_THEME_MAP[notificationType] || 'brand';
    const variantTheme = VARIANT_MAP[variantKey] || VARIANT_MAP.brand;

    if (variantKey === 'brand') {
        const [primary, secondary] = normalizeThemeColors(admin?.themeColors, DEFAULT_THEME_COLORS);
        return { ...variantTheme, primary, secondary };
    }

    return variantTheme;
};

const buildNotificationEmailTemplate = ({
    admin,
    recipient,
    subject,
    title,
    message,
    notificationType = 'general',
    palette,
    allowHtml = false,
    actionLabel = 'Open Portal',
    actionUrl = process.env.FRONTEND_URL || '',
    footerNote = 'This is an automated notification generated by your institute ERP.'
}) => {
    if (isFullHtmlDocument(message)) {
        return String(message);
    }

    const theme = resolveTemplateTheme({ admin, notificationType, palette });
    const instituteName = admin?.coachingName || 'Your Institute';
    const logoUrl = admin?.instituteLogo || '';
    const recipientName = recipient?.name || 'there';
    const supportEmail = admin?.instituteEmail || admin?.gmailEmail || admin?.email || '';
    const supportPhone = admin?.institutePhone || admin?.phone || '';
    const footerMeta = [supportEmail, supportPhone].filter(Boolean).join(' | ');
    const heading = title || subject || 'Notification Update';
    const bodyHtml = formatBodyHtml(message, allowHtml);
    const preheader = stripTags(message) || heading;
    const actionMarkup = actionUrl
        ? `<a href="${escapeHtml(actionUrl)}" style="display:inline-block;padding:12px 22px;border-radius:999px;background:${theme.primary};color:#ffffff;text-decoration:none;font-weight:700;font-size:14px;">${escapeHtml(actionLabel)}</a>`
        : '';

    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${escapeHtml(heading)}</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            background: #f4f7fb;
            font-family: Arial, Helvetica, sans-serif;
            color: #1f2937;
        }
        a { color: inherit; }
        @media only screen and (max-width: 640px) {
            .shell { padding: 18px !important; }
            .card { border-radius: 22px !important; }
            .section { padding: 24px !important; }
            .hero { padding: 28px 24px 20px !important; }
            .title { font-size: 26px !important; }
        }
    </style>
</head>
<body>
    <div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">
        ${escapeHtml(preheader)}
    </div>
    <div class="shell" style="padding: 32px 16px;">
        <div class="card" style="max-width: 640px; margin: 0 auto; background: #ffffff; border-radius: 28px; overflow: hidden; border: 1px solid #dbe3f0; box-shadow: 0 18px 46px rgba(15, 23, 42, 0.08);">
            <div class="hero" style="padding: 36px 36px 28px; background: linear-gradient(135deg, ${theme.primary} 0%, ${theme.secondary} 100%); color: #ffffff;">
                <div style="display:flex;justify-content:space-between;align-items:flex-start;gap:16px;flex-wrap:wrap;">
                    <div>
                        <div style="display:inline-block;padding:7px 12px;border-radius:999px;background:${theme.badgeBg};color:${theme.badgeText};font-size:12px;font-weight:700;letter-spacing:0.04em;text-transform:uppercase;">
                            ${escapeHtml(theme.label)}
                        </div>
                        <h1 class="title" style="margin:18px 0 10px;font-size:32px;line-height:1.15;font-weight:800;color:#ffffff;">
                            ${escapeHtml(heading)}
                        </h1>
                        <p style="margin:0;font-size:15px;line-height:1.6;color:rgba(255,255,255,0.92);">
                            A reusable notification format for important institute communication.
                        </p>
                    </div>
                    ${logoUrl ? `<img src="${escapeHtml(logoUrl)}" alt="${escapeHtml(instituteName)} logo" style="width:68px;height:68px;border-radius:18px;object-fit:cover;border:2px solid rgba(255,255,255,0.55);background:#ffffff;" />` : ''}
                </div>
            </div>
            <div class="section" style="padding: 32px 36px;">
                <div style="margin-bottom:24px;padding:16px 18px;border-radius:18px;border:1px solid ${theme.accentBorder};background:${theme.accentBg};color:${theme.accentText};font-size:14px;font-weight:600;">
                    Hello ${escapeHtml(recipientName)}, here is your latest update from ${escapeHtml(instituteName)}.
                </div>
                <div style="font-size:15px;line-height:1.7;color:#475569;">
                    ${bodyHtml}
                </div>
                ${actionMarkup ? `<div style="margin-top:28px;">${actionMarkup}</div>` : ''}
            </div>
        </div>
        <div style="max-width:640px;margin:16px auto 0;padding:0 8px;text-align:center;color:#64748b;font-size:12px;line-height:1.7;">
            <div style="font-weight:700;color:#334155;">${escapeHtml(instituteName)}</div>
            <div>${escapeHtml(footerNote)}</div>
            ${footerMeta ? `<div>${escapeHtml(footerMeta)}</div>` : ''}
        </div>
    </div>
</body>
</html>
`;
};

module.exports = {
    DEFAULT_THEME_COLORS,
    buildNotificationEmailTemplate,
    resolveTemplateTheme
};
